export const ITEMS_PER_PAGE = 10;

export const DUMMY_EMPLOYERS = [
  {
    id: "1",
    identificacao: "Empresa A",
    razaoSocial: "Empresa A LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "2",
    identificacao: "Empresa B",
    razaoSocial: "Empresa B LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "3",
    identificacao: "Empresa C",
    razaoSocial: "Empresa C LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "4",
    identificacao: "Empresa D",
    razaoSocial: "Empresa D LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "5",
    identificacao: "Empresa E",
    razaoSocial: "Empresa E LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "6",
    identificacao: "Empresa F",
    razaoSocial: "Empresa F LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "7",
    identificacao: "Empresa G",
    razaoSocial: "Empresa G LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "8",
    identificacao: "Empresa H",
    razaoSocial: "Empresa H LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "9",
    identificacao: "Empresa I",
    razaoSocial: "Empresa I LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "10",
    identificacao: "Empresa J",
    razaoSocial: "Empresa J LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "11",
    identificacao: "Empresa K",
    razaoSocial: "Empresa K LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "12",
    identificacao: "Empresa L",
    razaoSocial: "Empresa L LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
];

export const DUMMY_EMPLOYER_CONTACTS = [
  {
    id: "1",
    nome: "João Silva",
    departamento: "RH",
    telefone: "(11) 98765-4321",
    email: "joao@empresa.com.br",
  },
  {
    id: "2",
    nome: "Luana Santos",
    departamento: "RH",
    telefone: "(11) 98765-1234",
    email: "luana@empresa.com.br",
  },
  {
    id: "3",
    nome: "Maria Oliveira",
    departamento: "Financeiro",
    telefone: "(11) 96785-4231",
    email: "maria@empresa.com.br",
  },
  {
    id: "4",
    nome: "Carlos Pereira",
    departamento: "Financeiro",
    telefone: "(11) 99222-1324",
    email: "carlos@empresa.com.br",
  },
];
