import { Doctor } from "@/types/empregadores";

export const ITEMS_PER_PAGE = 10;

export const DUMMY_EMPLOYERS = [
  {
    id: "1",
    identificacao: "Empresa A",
    razaoSocial: "Empresa A LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "2",
    identificacao: "Empresa B",
    razaoSocial: "Empresa B LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "3",
    identificacao: "Empresa C",
    razaoSocial: "Empresa C LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "4",
    identificacao: "Empresa D",
    razaoSocial: "Empresa D LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "5",
    identificacao: "Empresa E",
    razaoSocial: "Empresa E LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "6",
    identificacao: "Empresa F",
    razaoSocial: "Empresa F LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "7",
    identificacao: "Empresa G",
    razaoSocial: "Empresa G LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "8",
    identificacao: "Empresa H",
    razaoSocial: "Empresa H LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "9",
    identificacao: "Empresa I",
    razaoSocial: "Empresa I LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "10",
    identificacao: "Empresa J",
    razaoSocial: "Empresa J LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
  {
    id: "11",
    identificacao: "Empresa K",
    razaoSocial: "Empresa K LTDA",
    situacao: "Ativo",
    tipo: "CPF",
    cidade: "São Paulo",
    uf: "SP",
  },
  {
    id: "12",
    identificacao: "Empresa L",
    razaoSocial: "Empresa L LTDA",
    situacao: "Inativo",
    tipo: "CNPJ",
    cidade: "Rio de Janeiro",
    uf: "RJ",
  },
];

export const DUMMY_EMPLOYER_CONTACTS = [
  {
    id: "1",
    nome: "João Silva",
    departamento: "RH",
    telefone: "(11) 98765-4321",
    email: "joao@empresa.com.br",
  },
  {
    id: "2",
    nome: "Luana Santos",
    departamento: "RH",
    telefone: "(11) 98765-1234",
    email: "luana@empresa.com.br",
  },
  {
    id: "3",
    nome: "Maria Oliveira",
    departamento: "Financeiro",
    telefone: "(11) 96785-4231",
    email: "maria@empresa.com.br",
  },
  {
    id: "4",
    nome: "Carlos Pereira",
    departamento: "Financeiro",
    telefone: "(11) 99222-1324",
    email: "carlos@empresa.com.br",
  },
];

export const DUMMY_EMPLOYER_SERVICE_UNIT = [
  {
    id: "1",
    unidade_atendimento: "BERTA CONSULTORIA  - (19.390.220/0001-05)",
    tabela_preco: "X",
  },
  {
    id: "2",
    unidade_atendimento: "MEDEIROS CONSULTORIA EM SSMA - (49.313.303/0001-53)",
    tabela_preco: "Y",
  },
  {
    id: "3",
    unidade_atendimento: "NMD CONSULTORIA EM SSMA  - (45.221.543/0001-77)",
    tabela_preco: "Z",
  },
];

export const DUMMY_EMPLOYER_ACCOUNTING = [
  {
    id: "1",
    razaoSocial: "Contabilidade A",
    nome: "Sr. Contador",
    telefone: "(11) 98199-1234",
    email: "ocontador@contabilidade.com.br",
  },
  {
    id: "2",
    razaoSocial: "Contabilidade B",
    nome: "Sra. Contador",
    telefone: "(11) 9100-1234",
    email: "acontadora@contabilidade.com.br",
  },
];

export const DUMMY_DOCTORS: Doctor[] = [
  {
    nome: "Adriana Teles de Andrade (199.351.938-61)",
    id: "1",
    cpf: "199.351.938-61",
    crm: "12345",
    uf: "SP",
  },
  {
    nome: "Ahmad Ali A. Rahim ()",
    id: "2",
    cpf: "015.949.510-55",
    crm: "14785",
    uf: "SP",
  },
  {
    nome: "Álvaro barnada ()",
    id: "3",
    cpf: "137.607.140-13",
    crm: "36985",
    uf: "SP",
  },
  {
    nome: "Karyme Aballa ()",
    id: "4",
    cpf: "294.201.970-00",
    crm: "25874",
    uf: "SP",
  },
  {
    nome: "Kennedy Castro Santos ()",
    id: "5",
    cpf: "698.464.780-03",
    crm: "98756",
    uf: "SP",
  },
  {
    nome: "Letícia Vieira da Silva (420.440.008-65)",
    id: "6",
    cpf: "420.440.008-65",
    crm: "65423",
    uf: "SP",
  },
  {
    nome: "Luis Alberto L. Cardoso ()",
    id: "7",
    cpf: "443.429.900-08",
    crm: "35748",
    uf: "SP",
  },
  {
    nome: "Samuel Vitor Barbosa ()",
    id: "8",
    cpf: "020.484.550-50",
    crm: "95164",
    uf: "SP",
  },
  {
    nome: "Sayd Ali El Malt (490.509.378-37)",
    id: "9",
    cpf: "490.509.378-37",
    crm: "19546",
    uf: "SP",
  },
  {
    nome: "Sebastião Lacerda Lopes Junior (491.451.691-87)",
    id: "10",
    cpf: "491.451.691-87",
    crm: "64289",
    uf: "SP",
  },
];
